spring:
    datasource:
      url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
      #schema: database/import.sql
      #sql-script-encoding: utf-8
      driverClassName: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

    thymeleaf:
      mode: HTML5
      encoding: utf-8
      servlet:
        content-type: text/html; charset=utf-8
      cache: false